apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratix-gitstore-job
  namespace: argocd
  labels:
    app.kubernetes.io/name: kratix-gitstore-job
spec:
  destination:
    namespace: kratix-platform-system
    server: "https://kubernetes.default.svc"
  source:
    repoURL: cnoe://manifests
    targetRevision: HEAD
    path: "."
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true