apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kratix-new-agent
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - clusterName: worker-1
            repoPath: worker-1
          - clusterName: worker-2
            repoPath: worker-2
  template:
    metadata:
      name: "kratix-new-agent-{{clusterName}}"
      labels:
        app.kubernetes.io/name: "kratix-new-agent-{{clusterName}}"
    spec:
      project: default
      destination:
        name: "{{clusterName}}" # name of the target cluster where the resources should be created
        # server: "https://kubernetes.default.svc"
      source:
        repoURL: cnoe://kratix-worload
        targetRevision: HEAD
        path: .
        helm:
          valuesObject:
            clusterName: "{{clusterName}}"
            giteaServer:
              url: https://gitea.cnoe.localtest.me:8443 # http://192.168.129.0:32223 (IP:NODE_PORT)
            gitKratix:
              org: kratix
              repository: state
              path: "{{repoPath}}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
