# Values to configure the resources:
# Application CR - kratix dependencies
# Application CR - kratix resources
# Secret         - Gitea server credentials

destination:
  name: #worker-1
  path: #worker-1

stateStore:
  kind: GitStateStore
  reference: gitea

  username: giteaAdmin
  password: developer

  gitOrgName: kratix
  gitStateRepoName: state
  gitApiUrl: https://gitea.cnoe.localtest.me:8443/api

labels:
  environment: dev
  cluster: worker-1
  team: team-a