apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kratix-new-destination
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - clusterName: worker1
            repoPath: worker-1
            environment: dev
            team: team-a
          - clusterName: worker2
            repoPath: worker-2
            environment: test
            team: team-b
  template:
    metadata:
      name: "kratix-new-destination-{{clusterName}}"
      labels:
        applicationName: "kratix-new-destination-{{clusterName}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io # enabling cascading deletion
    spec:
      project: default
      destination:
        server: "https://kubernetes.default.svc"
      source:
        repoURL: cnoe://new-destination
        targetRevision: HEAD
        path: .
        helm:
          valuesObject:
            destination:
              name: "{{clusterName}}"
              path: "{{repoPath}}"
            stateStore:
              kind: GitStateStore
              reference: gitea
            labels:
              environment: "{{environment}}"
              cluster: "{{clusterName}}"
              team: "{{team}}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
