apiVersion: v1
data:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIBsDCCAVWgAwIBAgIRAL7SWdNQZjBYTb4Ax+ZNwpAwCgYIKoZIzj0EAwIwEjEQ
    MA4GA1UEChMHY25vZS5pbzAeFw0yNTA0MTUxMjM1MjdaFw0yNjA0MTUxODM1Mjda
    MBIxEDAOBgNVBAoTB2Nub2UuaW8wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQC
    OEzympfnswvWPpdB+d1I4WtgADoi4CFnPk8PrCm0hIEJ0sudORjnK97LHkUEAWpv
    nasI1Y2Or0K7FwZowTyuo4GLMIGIMA4GA1UdDwEB/wQEAwIChDATBgNVHSUEDDAK
    BggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRBxY2bYChcityu
    LKC0UMH4OxEEbDAxBgNVHREEKjAoghFjbm9lLmxvY2FsdGVzdC5tZYITKi5jbm9l
    LmxvY2FsdGVzdC5tZTAKBggqhkjOPQQDAgNJADBGAiEAkzzAzOZTWfZ6nvYMqkCz
    Ml1X9EDQrkuBlZqv9qmfjCICIQCQVqhlP8+r42hPcWVbBghVmhyScMjolbBV5ZMU
    rOe2ig==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config-registry-cert
  namespace: tekton-pipelines
